package com.laibao.dubbo.hsf.rpc.serialization;

import com.google.protobuf.Message;

import java.util.Objects;

/**
 * ProtocolBuf Encoder
 * 
 */
public class PBEncoder implements Encoder {

	/**
	 *
	 * @param obj
	 * @return byte[]
	 */
	public byte[] encode(Object obj){
		Objects.requireNonNull(obj);
		if (!(obj instanceof Message)) {
			StringBuilder stringBuilder = new StringBuilder("Send object is not type of com.google.protobuf.Message,");
			stringBuilder.append("pls sure the object is generated by pb,object is: ")
						.append(obj);
			throw new RuntimeException(stringBuilder.toString());
		}
		try{
			Message message = (Message) obj;
			return message.toByteArray();
		}catch (Exception ex) {
			throw new RuntimeException("PB encode failure,",ex.getCause());
		}

	}

}
